dist: trusty
sudo: required
language: go

go:
- 1.10.x

env:
- MYSQL_IMAGE=mysql/mysql-server:5.5
- MYSQL_IMAGE=mysql/mysql-server:5.6
- MYSQL_IMAGE=mysql/mysql-server:5.7
- MYSQL_IMAGE=mysql/mysql-server:8.0
- MYSQL_IMAGE=mariadb:5.5
- MYSQL_IMAGE=mariadb:10.0
- MYSQL_IMAGE=mariadb:10.1
- MYSQL_IMAGE=mariadb:10.2
- MYSQL_IMAGE=mariadb:10.3
- MYSQL_IMAGE=percona/percona-server:5.6
- MYSQL_IMAGE=percona/percona-server:5.7
- MYSQL_IMAGE=percona/percona-server:8.0
- MYSQL_IMAGE=percona:5.5
- MYSQL_IMAGE=percona:5.6
- MYSQL_IMAGE=percona:5.7
- MYSQL_IMAGE=percona:8.0

services:
- docker

go_import_path: github.com/shatteredsilicon/mysqld_exporter

before_script:
- sudo service mysql stop
- docker --version
- docker-compose --version
- docker-compose up -d

script:
- make
- make test

notifications:
  email: false
