[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[override]]
  name = "github.com/prometheus/common"
  # Version before introducing kingpin.
  # https://github.com/prometheus/common/pull/96
  revision = "185c63bfc5a8c7a703687edb52940c895c818cb5"

[[override]]
  name = "golang.org/x/net"
  revision = "d866cfc389cec985d6fda2859936a575a55a3ab6"

[[override]]
  name = "github.com/shatteredsilicon/ssm-client"
  revision = "96459a7bd478a9e2b6beba95fa22c5472e4d7411"
